import React from 'react';

interface TermsOfServicePageProps {
  onBack: () => void;
  source: 'login' | 'dashboard' | 'createAccount';
}

const TermsOfServicePage: React.FC<TermsOfServicePageProps> = ({ onBack, source }) => {
  const getButtonText = (source: 'login' | 'dashboard' | 'createAccount') => {
    switch (source) {
      case 'dashboard':
        return 'Back to Dashboard';
      case 'createAccount':
        return 'Back to Account Creation';
      case 'login':
      default:
        return 'Back to Login';
    }
  };
  
  return (
    <div className="w-full max-w-3xl bg-white dark:bg-gray-800 rounded-lg sm:rounded-xl shadow-lg sm:shadow-2xl p-4 max-[360px]:p-3 min-[414px]:p-5 sm:p-6 border border-gray-200 dark:border-gray-700 transition-colors duration-300 animate-fade-in">
      <div className="space-y-6">
        <div className="text-center">
          <h1 className="text-2xl sm:text-3xl font-black text-[#DC143C] tracking-wider uppercase">
            G.R.E.T.E.L
          </h1>
          <h2 className="mt-4 text-xl sm:text-2xl font-bold text-gray-800 dark:text-gray-200">Terms of Service</h2>
          <p className="mt-2 text-xs sm:text-sm text-gray-500 dark:text-gray-400">Last Updated: October 26, 2025</p>
        </div>
        
        <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 space-y-4">
          <p>Please read these Terms of Service carefully before using the G.R.E.T.E.L application. Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms.</p>
          
          <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">1. Acceptance of Terms</h3>
          <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.</p>

          <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">2. Description of Service</h3>
          <p>G.R.E.T.E.L (General Response Engine & Task Execution Logic) is a personalized executive assistant AI designed to help you organize, manage, and optimize your professional workflow. The Service is provided "AS IS" and "AS AVAILABLE" without warranties of any kind.</p>

          <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">3. User Conduct</h3>
          <p>You agree not to use the Service for any unlawful purpose or to solicit others to perform or participate in any unlawful acts. You are responsible for all data, text, and other materials that you input into the Service.</p>
          
          <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">4. Disclaimer of Warranties</h3>
          <p>The Service is provided without any warranties, express or implied. We do not warrant that the Service will be uninterrupted, timely, secure, or error-free. The use of the AI's suggestions and outputs is at your own risk. We do not guarantee the accuracy or reliability of any information generated by the AI.</p>

          <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">5. Limitation of Liability</h3>
          <p>In no event shall G.R.E.T.E.L or its creators be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
          
          <h3 className="font-bold text-lg text-gray-800 dark:text-gray-200">6. Changes</h3>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will try to provide notice of any changes by posting the new Terms on this page.</p>

        </div>

        <div className="text-center pt-6">
          <button
            onClick={onBack}
            className="w-full sm:w-auto bg-[#DC143C] hover:bg-[#b81030] text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 ease-in-out transform hover:scale-105"
          >
            {getButtonText(source)}
          </button>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;